name: flutter_sound_processing
description: Flutter package designed for sound processing and analysis.
version: 0.0.1
homepage:

environment:
  sdk: '>=2.19.0-146.2.beta <3.0.0'
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        package: kg.cos9.flutter_sound_processing
        pluginClass: FlutterSoundProcessingPlugin
      ios:
        pluginClass: FlutterSoundProcessingPlugin